name: Build Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: 19-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build Node
        run: |
          npm run start
